### ISSUE TITLE
IOS Pod install error

### ISSUE THREAD

**Issue by dibyopra** [medyas/flutter_qiblah#48] opened 2024-03-27 04:51 UTC
No podspec found for `flutter_compass_v2` in `.symlinks/plugins/flutter_compass_v2/ios`

**Comment by lukeyuen701** [comment] 2024-03-28 06:36
Same issue: No podspec found for flutter_compass_v2 in .symlinks/plugins/flutter_compass_v2/ios

**Comment by medyas** [comment] 2024-03-28 10:18
@dibyopra @lukeyuen701 could you please test the latest version.

**Comment by lukeyuen701** [comment] 2024-03-28 10:27
> @dibyopra @lukeyuen701 could you please test the latest version.

Still not working with 3.0.1 : [!] No podspec found for `flutter_compass_v2` in `.symlinks/plugins/flutter_compass_v2/ios`

**Comment by medyas** [comment] 2024-03-28 10:32
@lukeyuen701 the issue is with `flutter_compass_v2` . I dont have a mac, could you clone https://github.com/medyas/flutter_compass_v2 run the example and try to fix the issue. Thanks!

**Comment by lukeyuen701** [comment] 2024-03-28 11:16
> @lukeyuen701 the issue is with `flutter_compass_v2` . I dont have a mac, could you clone https://github.com/medyas/flutter_compass_v2 run the example and try to fix the issue. Thanks!

1. Change the podspec name:  flutter_compass_v2/flutter_compass.podspec  ->  flutter_compass_v2/flutter_compass_v2.podspec

2. FlutterCompassPlugin : #import <flutter_compass_v2/flutter_compass-Swift.h>   ->   #import <flutter_compass_v2/flutter_compass_2-Swift.h>

**Comment by medyas** [comment] 2024-03-28 12:24
@lukeyuen701  Thanks!

**Comment by medyas** [comment] 2024-03-28 12:44
is it fixed in the latest version ?

**Comment by lukeyuen701** [comment] 2024-03-28 12:46
> is it fixed in the latest version ?

yes, it works great

**Closed** 2024-03-28 13:28 UTC
